<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageId>HKTKSDK.Windows</PackageId>
    <AssemblyName>HKTKSDK.Managed</AssemblyName>
    <Version>1.3.11</Version>
    <Authors>HKTK</Authors>
    <Description>HKTK Web OAuth SDK wrapper for Windows.</Description>
  </PropertyGroup>
</Project>
